/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as AuthenticatedFinanceiroIndexRouteImport } from './routes/_authenticated/financeiro.index'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes.index'
import { Route as AuthenticatedFinanceiroReceitasRouteImport } from './routes/_authenticated/financeiro.receitas'
import { Route as AuthenticatedFinanceiroFluxoCaixaRouteImport } from './routes/_authenticated/financeiro.fluxo-caixa'
import { Route as AuthenticatedFinanceiroDespesasRouteImport } from './routes/_authenticated/financeiro.despesas'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes.$id'
import { Route as AdminAdminUsuariosRouteImport } from './routes/_admin/admin.usuarios'
import { Route as AdminAdminPsicologosRouteImport } from './routes/_admin/admin.psicologos'
import { Route as AdminAdminConfiguracoesRouteImport } from './routes/_admin/admin.configuracoes'
import { Route as AdminAdminClientesRouteImport } from './routes/_admin/admin.clientes'
import { Route as AdminAdminAuditoriaRouteImport } from './routes/_admin/admin.auditoria'
import { Route as AuthenticatedClientesIdIndexRouteImport } from './routes/_authenticated/clientes.$id.index'
import { Route as AuthenticatedClientesIdRodaViaRouteImport } from './routes/_authenticated/clientes.$id.roda-via'
import { Route as AuthenticatedClientesIdRodaAdultoRouteImport } from './routes/_authenticated/clientes.$id.roda-adulto'
import { Route as AuthenticatedClientesIdRodaAdolescenteRouteImport } from './routes/_authenticated/clientes.$id.roda-adolescente'
import { Route as AuthenticatedClientesIdProntuarioRouteImport } from './routes/_authenticated/clientes.$id.prontuario'
import { Route as AuthenticatedClientesIdAnamneseRouteImport } from './routes/_authenticated/clientes.$id.anamnese'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedFinanceiroIndexRoute =
  AuthenticatedFinanceiroIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientesRoute,
  } as any)
const AuthenticatedFinanceiroReceitasRoute =
  AuthenticatedFinanceiroReceitasRouteImport.update({
    id: '/receitas',
    path: '/receitas',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroFluxoCaixaRoute =
  AuthenticatedFinanceiroFluxoCaixaRouteImport.update({
    id: '/fluxo-caixa',
    path: '/fluxo-caixa',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedFinanceiroDespesasRoute =
  AuthenticatedFinanceiroDespesasRouteImport.update({
    id: '/despesas',
    path: '/despesas',
    getParentRoute: () => AuthenticatedFinanceiroRoute,
  } as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientesRoute,
} as any)
const AdminAdminUsuariosRoute = AdminAdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminPsicologosRoute = AdminAdminPsicologosRouteImport.update({
  id: '/psicologos',
  path: '/psicologos',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminConfiguracoesRoute = AdminAdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminClientesRoute = AdminAdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAuditoriaRoute = AdminAdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AuthenticatedClientesIdIndexRoute =
  AuthenticatedClientesIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientesIdRoute,
  } as any)
const AuthenticatedClientesIdRodaViaRoute =
  AuthenticatedClientesIdRodaViaRouteImport.update({
    id: '/roda-via',
    path: '/roda-via',
    getParentRoute: () => AuthenticatedClientesIdRoute,
  } as any)
const AuthenticatedClientesIdRodaAdultoRoute =
  AuthenticatedClientesIdRodaAdultoRouteImport.update({
    id: '/roda-adulto',
    path: '/roda-adulto',
    getParentRoute: () => AuthenticatedClientesIdRoute,
  } as any)
const AuthenticatedClientesIdRodaAdolescenteRoute =
  AuthenticatedClientesIdRodaAdolescenteRouteImport.update({
    id: '/roda-adolescente',
    path: '/roda-adolescente',
    getParentRoute: () => AuthenticatedClientesIdRoute,
  } as any)
const AuthenticatedClientesIdProntuarioRoute =
  AuthenticatedClientesIdProntuarioRouteImport.update({
    id: '/prontuario',
    path: '/prontuario',
    getParentRoute: () => AuthenticatedClientesIdRoute,
  } as any)
const AuthenticatedClientesIdAnamneseRoute =
  AuthenticatedClientesIdAnamneseRouteImport.update({
    id: '/anamnese',
    path: '/anamnese',
    getParentRoute: () => AuthenticatedClientesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/agenda': typeof AuthenticatedAgendaRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRouteWithChildren
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/auditoria': typeof AdminAdminAuditoriaRoute
  '/admin/clientes': typeof AdminAdminClientesRoute
  '/admin/configuracoes': typeof AdminAdminConfiguracoesRoute
  '/admin/psicologos': typeof AdminAdminPsicologosRoute
  '/admin/usuarios': typeof AdminAdminUsuariosRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRouteWithChildren
  '/financeiro/despesas': typeof AuthenticatedFinanceiroDespesasRoute
  '/financeiro/fluxo-caixa': typeof AuthenticatedFinanceiroFluxoCaixaRoute
  '/financeiro/receitas': typeof AuthenticatedFinanceiroReceitasRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
  '/financeiro/': typeof AuthenticatedFinanceiroIndexRoute
  '/clientes/$id/anamnese': typeof AuthenticatedClientesIdAnamneseRoute
  '/clientes/$id/prontuario': typeof AuthenticatedClientesIdProntuarioRoute
  '/clientes/$id/roda-adolescente': typeof AuthenticatedClientesIdRodaAdolescenteRoute
  '/clientes/$id/roda-adulto': typeof AuthenticatedClientesIdRodaAdultoRoute
  '/clientes/$id/roda-via': typeof AuthenticatedClientesIdRodaViaRoute
  '/clientes/$id/': typeof AuthenticatedClientesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/agenda': typeof AuthenticatedAgendaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/auditoria': typeof AdminAdminAuditoriaRoute
  '/admin/clientes': typeof AdminAdminClientesRoute
  '/admin/configuracoes': typeof AdminAdminConfiguracoesRoute
  '/admin/psicologos': typeof AdminAdminPsicologosRoute
  '/admin/usuarios': typeof AdminAdminUsuariosRoute
  '/financeiro/despesas': typeof AuthenticatedFinanceiroDespesasRoute
  '/financeiro/fluxo-caixa': typeof AuthenticatedFinanceiroFluxoCaixaRoute
  '/financeiro/receitas': typeof AuthenticatedFinanceiroReceitasRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/financeiro': typeof AuthenticatedFinanceiroIndexRoute
  '/clientes/$id/anamnese': typeof AuthenticatedClientesIdAnamneseRoute
  '/clientes/$id/prontuario': typeof AuthenticatedClientesIdProntuarioRoute
  '/clientes/$id/roda-adolescente': typeof AuthenticatedClientesIdRodaAdolescenteRoute
  '/clientes/$id/roda-adulto': typeof AuthenticatedClientesIdRodaAdultoRoute
  '/clientes/$id/roda-via': typeof AuthenticatedClientesIdRodaViaRoute
  '/clientes/$id': typeof AuthenticatedClientesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRouteWithChildren
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_admin/admin/auditoria': typeof AdminAdminAuditoriaRoute
  '/_admin/admin/clientes': typeof AdminAdminClientesRoute
  '/_admin/admin/configuracoes': typeof AdminAdminConfiguracoesRoute
  '/_admin/admin/psicologos': typeof AdminAdminPsicologosRoute
  '/_admin/admin/usuarios': typeof AdminAdminUsuariosRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRouteWithChildren
  '/_authenticated/financeiro/despesas': typeof AuthenticatedFinanceiroDespesasRoute
  '/_authenticated/financeiro/fluxo-caixa': typeof AuthenticatedFinanceiroFluxoCaixaRoute
  '/_authenticated/financeiro/receitas': typeof AuthenticatedFinanceiroReceitasRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/financeiro/': typeof AuthenticatedFinanceiroIndexRoute
  '/_authenticated/clientes/$id/anamnese': typeof AuthenticatedClientesIdAnamneseRoute
  '/_authenticated/clientes/$id/prontuario': typeof AuthenticatedClientesIdProntuarioRoute
  '/_authenticated/clientes/$id/roda-adolescente': typeof AuthenticatedClientesIdRodaAdolescenteRoute
  '/_authenticated/clientes/$id/roda-adulto': typeof AuthenticatedClientesIdRodaAdultoRoute
  '/_authenticated/clientes/$id/roda-via': typeof AuthenticatedClientesIdRodaViaRoute
  '/_authenticated/clientes/$id/': typeof AuthenticatedClientesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/agenda'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/financeiro'
    | '/relatorios'
    | '/auth/callback'
    | '/admin/auditoria'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/psicologos'
    | '/admin/usuarios'
    | '/clientes/$id'
    | '/financeiro/despesas'
    | '/financeiro/fluxo-caixa'
    | '/financeiro/receitas'
    | '/clientes/'
    | '/financeiro/'
    | '/clientes/$id/anamnese'
    | '/clientes/$id/prontuario'
    | '/clientes/$id/roda-adolescente'
    | '/clientes/$id/roda-adulto'
    | '/clientes/$id/roda-via'
    | '/clientes/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/agenda'
    | '/configuracoes'
    | '/dashboard'
    | '/relatorios'
    | '/auth/callback'
    | '/admin/auditoria'
    | '/admin/clientes'
    | '/admin/configuracoes'
    | '/admin/psicologos'
    | '/admin/usuarios'
    | '/financeiro/despesas'
    | '/financeiro/fluxo-caixa'
    | '/financeiro/receitas'
    | '/clientes'
    | '/financeiro'
    | '/clientes/$id/anamnese'
    | '/clientes/$id/prontuario'
    | '/clientes/$id/roda-adolescente'
    | '/clientes/$id/roda-adulto'
    | '/clientes/$id/roda-via'
    | '/clientes/$id'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_admin/admin'
    | '/_authenticated/agenda'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/financeiro'
    | '/_authenticated/relatorios'
    | '/auth/callback'
    | '/_admin/admin/auditoria'
    | '/_admin/admin/clientes'
    | '/_admin/admin/configuracoes'
    | '/_admin/admin/psicologos'
    | '/_admin/admin/usuarios'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/financeiro/despesas'
    | '/_authenticated/financeiro/fluxo-caixa'
    | '/_authenticated/financeiro/receitas'
    | '/_authenticated/clientes/'
    | '/_authenticated/financeiro/'
    | '/_authenticated/clientes/$id/anamnese'
    | '/_authenticated/clientes/$id/prontuario'
    | '/_authenticated/clientes/$id/roda-adolescente'
    | '/_authenticated/clientes/$id/roda-adulto'
    | '/_authenticated/clientes/$id/roda-via'
    | '/_authenticated/clientes/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/financeiro/': {
      id: '/_authenticated/financeiro/'
      path: '/'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof AuthenticatedFinanceiroIndexRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/_authenticated/financeiro/receitas': {
      id: '/_authenticated/financeiro/receitas'
      path: '/receitas'
      fullPath: '/financeiro/receitas'
      preLoaderRoute: typeof AuthenticatedFinanceiroReceitasRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/fluxo-caixa': {
      id: '/_authenticated/financeiro/fluxo-caixa'
      path: '/fluxo-caixa'
      fullPath: '/financeiro/fluxo-caixa'
      preLoaderRoute: typeof AuthenticatedFinanceiroFluxoCaixaRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/financeiro/despesas': {
      id: '/_authenticated/financeiro/despesas'
      path: '/despesas'
      fullPath: '/financeiro/despesas'
      preLoaderRoute: typeof AuthenticatedFinanceiroDespesasRouteImport
      parentRoute: typeof AuthenticatedFinanceiroRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/_admin/admin/usuarios': {
      id: '/_admin/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminAdminUsuariosRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/psicologos': {
      id: '/_admin/admin/psicologos'
      path: '/psicologos'
      fullPath: '/admin/psicologos'
      preLoaderRoute: typeof AdminAdminPsicologosRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/configuracoes': {
      id: '/_admin/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminAdminConfiguracoesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/clientes': {
      id: '/_admin/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminAdminClientesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/auditoria': {
      id: '/_admin/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAdminAuditoriaRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_authenticated/clientes/$id/': {
      id: '/_authenticated/clientes/$id/'
      path: '/'
      fullPath: '/clientes/$id/'
      preLoaderRoute: typeof AuthenticatedClientesIdIndexRouteImport
      parentRoute: typeof AuthenticatedClientesIdRoute
    }
    '/_authenticated/clientes/$id/roda-via': {
      id: '/_authenticated/clientes/$id/roda-via'
      path: '/roda-via'
      fullPath: '/clientes/$id/roda-via'
      preLoaderRoute: typeof AuthenticatedClientesIdRodaViaRouteImport
      parentRoute: typeof AuthenticatedClientesIdRoute
    }
    '/_authenticated/clientes/$id/roda-adulto': {
      id: '/_authenticated/clientes/$id/roda-adulto'
      path: '/roda-adulto'
      fullPath: '/clientes/$id/roda-adulto'
      preLoaderRoute: typeof AuthenticatedClientesIdRodaAdultoRouteImport
      parentRoute: typeof AuthenticatedClientesIdRoute
    }
    '/_authenticated/clientes/$id/roda-adolescente': {
      id: '/_authenticated/clientes/$id/roda-adolescente'
      path: '/roda-adolescente'
      fullPath: '/clientes/$id/roda-adolescente'
      preLoaderRoute: typeof AuthenticatedClientesIdRodaAdolescenteRouteImport
      parentRoute: typeof AuthenticatedClientesIdRoute
    }
    '/_authenticated/clientes/$id/prontuario': {
      id: '/_authenticated/clientes/$id/prontuario'
      path: '/prontuario'
      fullPath: '/clientes/$id/prontuario'
      preLoaderRoute: typeof AuthenticatedClientesIdProntuarioRouteImport
      parentRoute: typeof AuthenticatedClientesIdRoute
    }
    '/_authenticated/clientes/$id/anamnese': {
      id: '/_authenticated/clientes/$id/anamnese'
      path: '/anamnese'
      fullPath: '/clientes/$id/anamnese'
      preLoaderRoute: typeof AuthenticatedClientesIdAnamneseRouteImport
      parentRoute: typeof AuthenticatedClientesIdRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminAuditoriaRoute: typeof AdminAdminAuditoriaRoute
  AdminAdminClientesRoute: typeof AdminAdminClientesRoute
  AdminAdminConfiguracoesRoute: typeof AdminAdminConfiguracoesRoute
  AdminAdminPsicologosRoute: typeof AdminAdminPsicologosRoute
  AdminAdminUsuariosRoute: typeof AdminAdminUsuariosRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminAuditoriaRoute: AdminAdminAuditoriaRoute,
  AdminAdminClientesRoute: AdminAdminClientesRoute,
  AdminAdminConfiguracoesRoute: AdminAdminConfiguracoesRoute,
  AdminAdminPsicologosRoute: AdminAdminPsicologosRoute,
  AdminAdminUsuariosRoute: AdminAdminUsuariosRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthenticatedClientesIdRouteChildren {
  AuthenticatedClientesIdAnamneseRoute: typeof AuthenticatedClientesIdAnamneseRoute
  AuthenticatedClientesIdProntuarioRoute: typeof AuthenticatedClientesIdProntuarioRoute
  AuthenticatedClientesIdRodaAdolescenteRoute: typeof AuthenticatedClientesIdRodaAdolescenteRoute
  AuthenticatedClientesIdRodaAdultoRoute: typeof AuthenticatedClientesIdRodaAdultoRoute
  AuthenticatedClientesIdRodaViaRoute: typeof AuthenticatedClientesIdRodaViaRoute
  AuthenticatedClientesIdIndexRoute: typeof AuthenticatedClientesIdIndexRoute
}

const AuthenticatedClientesIdRouteChildren: AuthenticatedClientesIdRouteChildren =
  {
    AuthenticatedClientesIdAnamneseRoute: AuthenticatedClientesIdAnamneseRoute,
    AuthenticatedClientesIdProntuarioRoute:
      AuthenticatedClientesIdProntuarioRoute,
    AuthenticatedClientesIdRodaAdolescenteRoute:
      AuthenticatedClientesIdRodaAdolescenteRoute,
    AuthenticatedClientesIdRodaAdultoRoute:
      AuthenticatedClientesIdRodaAdultoRoute,
    AuthenticatedClientesIdRodaViaRoute: AuthenticatedClientesIdRodaViaRoute,
    AuthenticatedClientesIdIndexRoute: AuthenticatedClientesIdIndexRoute,
  }

const AuthenticatedClientesIdRouteWithChildren =
  AuthenticatedClientesIdRoute._addFileChildren(
    AuthenticatedClientesIdRouteChildren,
  )

interface AuthenticatedClientesRouteChildren {
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRouteWithChildren
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
}

const AuthenticatedClientesRouteChildren: AuthenticatedClientesRouteChildren = {
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRouteWithChildren,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
}

const AuthenticatedClientesRouteWithChildren =
  AuthenticatedClientesRoute._addFileChildren(
    AuthenticatedClientesRouteChildren,
  )

interface AuthenticatedFinanceiroRouteChildren {
  AuthenticatedFinanceiroDespesasRoute: typeof AuthenticatedFinanceiroDespesasRoute
  AuthenticatedFinanceiroFluxoCaixaRoute: typeof AuthenticatedFinanceiroFluxoCaixaRoute
  AuthenticatedFinanceiroReceitasRoute: typeof AuthenticatedFinanceiroReceitasRoute
  AuthenticatedFinanceiroIndexRoute: typeof AuthenticatedFinanceiroIndexRoute
}

const AuthenticatedFinanceiroRouteChildren: AuthenticatedFinanceiroRouteChildren =
  {
    AuthenticatedFinanceiroDespesasRoute: AuthenticatedFinanceiroDespesasRoute,
    AuthenticatedFinanceiroFluxoCaixaRoute:
      AuthenticatedFinanceiroFluxoCaixaRoute,
    AuthenticatedFinanceiroReceitasRoute: AuthenticatedFinanceiroReceitasRoute,
    AuthenticatedFinanceiroIndexRoute: AuthenticatedFinanceiroIndexRoute,
  }

const AuthenticatedFinanceiroRouteWithChildren =
  AuthenticatedFinanceiroRoute._addFileChildren(
    AuthenticatedFinanceiroRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRouteWithChildren
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRouteWithChildren
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRouteWithChildren,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRouteWithChildren,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
