// This file is automatically generated and enhanced with key sanitization.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const VALID_ANON_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkaXhuZHR2ZGJvcndnZGl6Z3FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4MzQ0MjIsImV4cCI6MjA1MzQxMDQyMn0.X1ArgGa46Hkyg13d3oDPqw_aZJiY4M5';

function sanitizeSupabaseKey(key?: string): string {
  if (!key || typeof key !== 'string' || key.startsWith('sb_publishable_') || !key.startsWith('eyJ')) {
    return VALID_ANON_KEY;
  }
  return key.trim();
}

function createSupabaseClient() {
  const rawUrl =
    import.meta.env.VITE_SUPABASE_URL ||
    (typeof process !== 'undefined' && (process.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL)) ||
    'https://fdixndtvdborwgdizgqn.supabase.co';

  const rawKey =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    (typeof process !== 'undefined' && (process.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY)) ||
    VALID_ANON_KEY;

  const SUPABASE_URL = rawUrl.trim();
  const SUPABASE_PUBLISHABLE_KEY = sanitizeSupabaseKey(rawKey);

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      flowType: 'pkce',
      ...(typeof window !== 'undefined' && {
        redirectTo: `${window.location.origin}/auth/callback`,
      }),
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
